server:
  port: 8080
  servlet:
    context-path: /shopping

spring:
  datasource:
    url: jdbc:h2:mem:shopdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    user:
      name: user
      password: 123
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      prefix: /static/
#      suffix: .jsp
